# Generated by chain-rpc-balancer. Edit nodes.json and regenerate instead of editing this file.

global
    log /dev/log local0
    maxconn 4096
    stats socket /run/haproxy/admin.sock mode 660 level admin
    user haproxy
    group haproxy

defaults
    mode http
    log global
    option httplog
    option dontlognull
    option forwardfor
    timeout connect 3s
    timeout client 30s
    timeout server 30s
    timeout http-request 10s
    timeout tunnel 1h
    timeout check 3s
    timeout queue 10s

frontend rpc
{{BIND_LINES}}
    monitor-uri /lb-health
    monitor fail if { nbsrv(be_read) lt 1 }
{{REDIRECT_LINES}}
    http-request set-header X-Forwarded-Proto https if { ssl_fc }
{{STATUS_FRONTEND_LINES}}
{{CORS_LINES}}
    option http-buffer-request
    acl is_broadcast req.body -m sub broadcast_transaction
    acl is_websocket hdr(upgrade) -i websocket
{{CAPTURE_LINES}}
{{STATUS_ROUTE_LINES}}
    use_backend be_ws if is_websocket
    use_backend be_broadcast if is_broadcast
    default_backend be_read

# Reads are idempotent, so failures are retried on another node. Timeouts are not
# retried, so one slow query can't spread to (and fail-check) every node.
backend be_read
    balance leastconn
    option httpchk GET /
    http-check expect status 200
    retry-on conn-failure empty-response 502 503 504
    retries 2
    option redispatch 1
    default-server inter 3s fastinter 1s fall 2 rise 3 slowstart 30s observe layer7 error-limit 5 on-error fail-check{{NODE_LIMIT}}
{{SERVER_LINES}}

# A timed-out broadcast may already be in the mempool, so only retry when the connection never opened.
backend be_broadcast
    balance leastconn
    option httpchk GET /
    http-check expect status 200
    retry-on conn-failure
    retries 2
    option redispatch 1
    default-server inter 3s fastinter 1s fall 2 rise 3 slowstart 30s observe layer7 error-limit 5 on-error fail-check{{NODE_LIMIT}}
{{SERVER_LINES}}

# WebSockets hold a connection for their whole life, so they skip the per-node limit.
backend be_ws
    balance leastconn
    option httpchk GET /
    http-check expect status 200
    retry-on conn-failure
    retries 2
    option redispatch 1
    default-server inter 3s fastinter 1s fall 2 rise 3 slowstart 30s
{{SERVER_LINES}}

{{STATUS_BACKEND_LINES}}
listen stats
    bind {{STATS_BIND}}
    stats enable
    stats uri /
    stats refresh 10s
    stats hide-version
    stats auth {{STATS_AUTH}}
